### ISSUE TITLE
When using commands with bot-refence (ex: /my_command@bot_id) - command will not be processed.

### ISSUE THREAD

**Issue by romasha89** [chesn0k/drupal_telegram_sdk#6]
Issue in this line:
https://github.com/chesn0k/drupal_telegram_sdk/blob/b8cc5c03df78db6c446e90b0bd2159eb78e58e17/src/TelegramProcessor/TelegramCommandProcessor.php#L105
I believe, third argument ($before_needle) in func **stristr** should be set to TRUE in this case to make it work correctly: `stristr($command, '@', TRUE)`.

**Comment by chesn0k** [comment]
Oh really, thanks. I will fix it tomorrow or you can do it.

**Comment by chesn0k** [comment]
Made a new release with this fix.

**Comment by romasha89** [comment]
Great, thx a lot!
